name: balenaCloud build

on:
 pull_request:
    types: 
      - closed
    branches:
      - main

jobs:
  balena_cloud_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: sevets/traindisplays
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
